@butentaEndpoint = http://localhost:5125/api/v1/accounting/sti/butenta-vat-return

POST {{butentaEndpoint}}/submit-trade/1

###

GET {{butentaEndpoint}}/trade-declaration/1
Accept: application/json
Content-Type: application/json

###
