@DataEntry_API_IP = http://localhost:5125/api/v1/accounting/data-type

POST {{DataEntry_API_IP}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "CreatorId": 1,
    "Description": "Description of the field",
    "InstanceId": 1,
    "Name": "Name"
}

###

DELETE {{DataEntry_API_IP}}/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

PUT {{DataEntry_API_IP}}/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Description": 1,
    "Id": 1,
    "ManagerId": 1,
    "Name": "Name Edited"
}

###

GET {{DataEntry_API_IP}}/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

GET {{DataEntry_API_IP}}?instanceId=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}