@Instance_API_IP = http://localhost:5125/api/v1/accounting/instance

POST {{Instance_API_IP}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "CreatorId": 1,
  "Description": "First Instance To Be Created By The Creator",
  "Name": "First Instance"
}

###

DELETE {{Instance_API_IP}}/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

PUT {{Instance_API_IP}}/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "Description": "Second Instance To Be Created By The Creator",
  "Id": 2,
  "Name": "Second Instance"
}

###

GET {{Instance_API_IP}}/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

GET {{Instance_API_IP}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}