@InstanceUserMeta_API_IP = http://localhost:5125/api/v1/accounting/instance-user-meta

POST {{InstanceUserMeta_API_IP}}

{
    "InstanceId": 1,
    "UserId": "2",
    "ManagerId": "1"
}

###

DELETE {{InstanceUserMeta_API_IP}}/1

###

GET {{InstanceUserMeta_API_IP}}/1

###

GET {{InstanceUserMeta_API_IP}}?instanceId=1