import {User} from './user.model';

export interface IsoCountry {
  code: IsoCountryCode;
  name: string;
}

export const getUserIsoCountryLabel = (user?: User | null): string => {
  if (user == null) {
    return getDefaultIsoCountry().name;
  }

  return getIsoCountryByCode(user.country)?.name || getDefaultIsoCountry().name;
}

export const getIsoCountryLabel = (code?: IsoCountryCode | null): string => {
  if (code == null) {
    return getDefaultIsoCountry().name;
  }

  return getIsoCountryByCode(code).name;
}

export const getDefaultIsoCountry = (): IsoCountry => {
  return IsoCountries.find(c => c.code === IsoCountryCode.LT)!;
}

export const getIsoCountryByCode = (code: IsoCountryCode): IsoCountry => {
  return IsoCountries.find(c => c.code === code) || getDefaultIsoCountry();
}

export enum IsoCountryCode {
  AF,
  AX,
  AL,
  DZ,
  AS,
  AD,
  AO,
  AI,
  AQ,
  AG,
  AR,
  AM,
  AW,
  AU,
  AT,
  AZ,
  BS,
  BH,
  BD,
  BB,
  BY,
  BE,
  BZ,
  BJ,
  BM,
  BT,
  BO,
  BQ,
  BA,
  BW,
  BV,
  BR,
  IO,
  BN,
  BG,
  BF,
  BI,
  KH,
  CM,
  CA,
  CV,
  KY,
  CF,
  TD,
  CL,
  CN,
  CX,
  CC,
  CO,
  KM,
  CG,
  CD,
  CK,
  CR,
  CI,
  HR,
  CU,
  CW,
  CY,
  CZ,
  DK,
  DJ,
  DM,
  DO,
  EC,
  EG,
  SV,
  GQ,
  ER,
  EE,
  ET,
  FK,
  FO,
  FJ,
  FI,
  FR,
  GF,
  PF,
  TF,
  GA,
  GM,
  GE,
  DE,
  GH,
  GI,
  GR,
  GL,
  GD,
  GP,
  GU,
  GT,
  GG,
  GN,
  GW,
  GY,
  HT,
  HM,
  VA,
  HN,
  HK,
  HU,
  IS,
  IN,
  ID,
  IR,
  IQ,
  IE,
  IM,
  IL,
  IT,
  JM,
  JP,
  JE,
  JO,
  KZ,
  KE,
  KI,
  KP,
  KR,
  KW,
  KG,
  LA,
  LV,
  LB,
  LS,
  LR,
  LY,
  LI,
  LT,
  LU,
  MO,
  MK,
  MG,
  MW,
  MY,
  MV,
  ML,
  MT,
  MH,
  MQ,
  MR,
  MU,
  YT,
  MX,
  FM,
  MD,
  MC,
  MN,
  ME,
  MS,
  MA,
  MZ,
  MM,
  NA,
  NR,
  NP,
  NL,
  NC,
  NZ,
  NI,
  NE,
  NG,
  NU,
  NF,
  MP,
  NO,
  OM,
  PK,
  PW,
  PS,
  PA,
  PG,
  PY,
  PE,
  PH,
  PN,
  PL,
  PT,
  PR,
  QA,
  RE,
  RO,
  RU,
  RW,
  BL,
  SH,
  KN,
  LC,
  MF,
  PM,
  VC,
  WS,
  SM,
  ST,
  SA,
  SN,
  RS,
  SC,
  SL,
  SG,
  SX,
  SK,
  SI,
  SB,
  SO,
  ZA,
  GS,
  SS,
  ES,
  LK,
  SD,
  SR,
  SJ,
  SZ,
  SE,
  CH,
  SY,
  TW,
  TJ,
  TZ,
  TH,
  TL,
  TG,
  TK,
  TO,
  TT,
  TN,
  TR,
  TM,
  TC,
  TV,
  UG,
  UA,
  AE,
  GB,
  US,
  UM,
  UY,
  UZ,
  VU,
  VE,
  VN,
  VG,
  VI,
  WF,
  EH,
  YE,
  ZM,
  ZW
}

export const IsoCountries: IsoCountry[] = [
  {code: IsoCountryCode.AF, name: "Afghanistan"},
  {code: IsoCountryCode.AX, name: "Aland Islands"},
  {code: IsoCountryCode.AL, name: "Albania"},
  {code: IsoCountryCode.DZ, name: "Algeria"},
  {code: IsoCountryCode.AS, name: "American Samoa"},
  {code: IsoCountryCode.AD, name: "Andorra"},
  {code: IsoCountryCode.AO, name: "Angola"},
  {code: IsoCountryCode.AI, name: "Anguilla"},
  {code: IsoCountryCode.AQ, name: "Antarctica"},
  {code: IsoCountryCode.AG, name: "Antigua and Barbuda"},
  {code: IsoCountryCode.AR, name: "Argentina"},
  {code: IsoCountryCode.AM, name: "Armenia"},
  {code: IsoCountryCode.AW, name: "Aruba"},
  {code: IsoCountryCode.AU, name: "Australia"},
  {code: IsoCountryCode.AT, name: "Austria"},
  {code: IsoCountryCode.AZ, name: "Azerbaijan"},
  {code: IsoCountryCode.BS, name: "Bahamas"},
  {code: IsoCountryCode.BH, name: "Bahrain"},
  {code: IsoCountryCode.BD, name: "Bangladesh"},
  {code: IsoCountryCode.BB, name: "Barbados"},
  {code: IsoCountryCode.BY, name: "Belarus"},
  {code: IsoCountryCode.BE, name: "Belgium"},
  {code: IsoCountryCode.BZ, name: "Belize"},
  {code: IsoCountryCode.BJ, name: "Benin"},
  {code: IsoCountryCode.BM, name: "Bermuda"},
  {code: IsoCountryCode.BT, name: "Bhutan"},
  {code: IsoCountryCode.BO, name: "Bolivia"},
  {code: IsoCountryCode.BQ, name: "Bonaire"},
  {code: IsoCountryCode.BA, name: "Bosnia and Herzegovina"},
  {code: IsoCountryCode.BW, name: "Botswana"},
  {code: IsoCountryCode.BV, name: "Bouvet Island"},
  {code: IsoCountryCode.BR, name: "Brazil"},
  {code: IsoCountryCode.IO, name: "British Indian Ocean Territory"},
  {code: IsoCountryCode.BN, name: "Brunei"},
  {code: IsoCountryCode.BG, name: "Bulgaria"},
  {code: IsoCountryCode.BF, name: "Burkina Faso"},
  {code: IsoCountryCode.BI, name: "Burundi"},
  {code: IsoCountryCode.KH, name: "Cambodia"},
  {code: IsoCountryCode.CM, name: "Cameroon"},
  {code: IsoCountryCode.CA, name: "Canada"},
  {code: IsoCountryCode.CV, name: "Cape Verde"},
  {code: IsoCountryCode.KY, name: "Cayman Islands"},
  {code: IsoCountryCode.CF, name: "Central African Republic"},
  {code: IsoCountryCode.TD, name: "Chad"},
  {code: IsoCountryCode.CL, name: "Chile"},
  {code: IsoCountryCode.CN, name: "China"},
  {code: IsoCountryCode.CX, name: "Christmas Island"},
  {code: IsoCountryCode.CC, name: "Cocos (Keeling) Islands"},
  {code: IsoCountryCode.CO, name: "Colombia"},
  {code: IsoCountryCode.KM, name: "Comoros"},
  {code: IsoCountryCode.CG, name: "Congo"},
  {code: IsoCountryCode.CD, name: "Congo (Kinshasa)"},
  {code: IsoCountryCode.CK, name: "Cook Islands"},
  {code: IsoCountryCode.CR, name: "Costa Rica"},
  {code: IsoCountryCode.CI, name: "Ivory Coast"},
  {code: IsoCountryCode.HR, name: "Croatia"},
  {code: IsoCountryCode.CU, name: "Cuba"},
  {code: IsoCountryCode.CW, name: "Curacao"},
  {code: IsoCountryCode.CY, name: "Cyprus"},
  {code: IsoCountryCode.CZ, name: "Czech Republic"},
  {code: IsoCountryCode.DK, name: "Denmark"},
  {code: IsoCountryCode.DJ, name: "Djibouti"},
  {code: IsoCountryCode.DM, name: "Dominica"},
  {code: IsoCountryCode.DO, name: "Dominican Republic"},
  {code: IsoCountryCode.EC, name: "Ecuador"},
  {code: IsoCountryCode.EG, name: "Egypt"},
  {code: IsoCountryCode.SV, name: "El Salvador"},
  {code: IsoCountryCode.GQ, name: "Equatorial Guinea"},
  {code: IsoCountryCode.ER, name: "Eritrea"},
  {code: IsoCountryCode.EE, name: "Estonia"},
  {code: IsoCountryCode.ET, name: "Ethiopia"},
  {code: IsoCountryCode.FK, name: "Falkland Islands"},
  {code: IsoCountryCode.FO, name: "Faroe Islands"},
  {code: IsoCountryCode.FJ, name: "Fiji"},
  {code: IsoCountryCode.FI, name: "Finland"},
  {code: IsoCountryCode.FR, name: "France"},
  {code: IsoCountryCode.GF, name: "French Guiana"},
  {code: IsoCountryCode.PF, name: "French Polynesia"},
  {code: IsoCountryCode.TF, name: "French Southern Territories"},
  {code: IsoCountryCode.GA, name: "Gabon"},
  {code: IsoCountryCode.GM, name: "Gambia"},
  {code: IsoCountryCode.GE, name: "Georgia"},
  {code: IsoCountryCode.DE, name: "Germany"},
  {code: IsoCountryCode.GH, name: "Ghana"},
  {code: IsoCountryCode.GI, name: "Gibraltar"},
  {code: IsoCountryCode.GR, name: "Greece"},
  {code: IsoCountryCode.GL, name: "Greenland"},
  {code: IsoCountryCode.GD, name: "Grenada"},
  {code: IsoCountryCode.GP, name: "Guadeloupe"},
  {code: IsoCountryCode.GU, name: "Guam"},
  {code: IsoCountryCode.GT, name: "Guatemala"},
  {code: IsoCountryCode.GG, name: "Guernsey"},
  {code: IsoCountryCode.GN, name: "Guinea"},
  {code: IsoCountryCode.GW, name: "Guinea-Bissau"},
  {code: IsoCountryCode.GY, name: "Guyana"},
  {code: IsoCountryCode.HT, name: "Haiti"},
  {code: IsoCountryCode.HM, name: "Heard Island and McDonald Islands"},
  {code: IsoCountryCode.VA, name: "Vatican City"},
  {code: IsoCountryCode.HN, name: "Honduras"},
  {code: IsoCountryCode.HK, name: "Hong Kong"},
  {code: IsoCountryCode.HU, name: "Hungary"},
  {code: IsoCountryCode.IS, name: "Iceland"},
  {code: IsoCountryCode.IN, name: "India"},
  {code: IsoCountryCode.ID, name: "Indonesia"},
  {code: IsoCountryCode.IR, name: "Iran"},
  {code: IsoCountryCode.IQ, name: "Iraq"},
  {code: IsoCountryCode.IE, name: "Ireland"},
  {code: IsoCountryCode.IM, name: "Isle of Man"},
  {code: IsoCountryCode.IL, name: "Israel"},
  {code: IsoCountryCode.IT, name: "Italy"},
  {code: IsoCountryCode.JM, name: "Jamaica"},
  {code: IsoCountryCode.JP, name: "Japan"},
  {code: IsoCountryCode.JE, name: "Jersey"},
  {code: IsoCountryCode.JO, name: "Jordan"},
  {code: IsoCountryCode.KZ, name: "Kazakhstan"},
  {code: IsoCountryCode.KE, name: "Kenya"},
  {code: IsoCountryCode.KI, name: "Kiribati"},
  {code: IsoCountryCode.KP, name: "North Korea"},
  {code: IsoCountryCode.KR, name: "South Korea"},
  {code: IsoCountryCode.KW, name: "Kuwait"},
  {code: IsoCountryCode.KG, name: "Kyrgyzstan"},
  {code: IsoCountryCode.LA, name: "Laos"},
  {code: IsoCountryCode.LV, name: "Latvia"},
  {code: IsoCountryCode.LB, name: "Lebanon"},
  {code: IsoCountryCode.LS, name: "Lesotho"},
  {code: IsoCountryCode.LR, name: "Liberia"},
  {code: IsoCountryCode.LY, name: "Libya"},
  {code: IsoCountryCode.LI, name: "Liechtenstein"},
  {code: IsoCountryCode.LT, name: "Lithuania"},
  {code: IsoCountryCode.LU, name: "Luxembourg"},
  {code: IsoCountryCode.MO, name: "Macau"},
  {code: IsoCountryCode.MK, name: "North Macedonia"},
  {code: IsoCountryCode.MG, name: "Madagascar"},
  {code: IsoCountryCode.MW, name: "Malawi"},
  {code: IsoCountryCode.MY, name: "Malaysia"},
  {code: IsoCountryCode.MV, name: "Maldives"},
  {code: IsoCountryCode.ML, name: "Mali"},
  {code: IsoCountryCode.MT, name: "Malta"},
  {code: IsoCountryCode.MH, name: "Marshall Islands"},
  {code: IsoCountryCode.MQ, name: "Martinique"},
  {code: IsoCountryCode.MR, name: "Mauritania"},
  {code: IsoCountryCode.MU, name: "Mauritius"},
  {code: IsoCountryCode.YT, name: "Mayotte"},
  {code: IsoCountryCode.MX, name: "Mexico"},
  {code: IsoCountryCode.FM, name: "Micronesia"},
  {code: IsoCountryCode.MD, name: "Moldova"},
  {code: IsoCountryCode.MC, name: "Monaco"},
  {code: IsoCountryCode.MN, name: "Mongolia"},
  {code: IsoCountryCode.ME, name: "Montenegro"},
  {code: IsoCountryCode.MS, name: "Montserrat"},
  {code: IsoCountryCode.MA, name: "Morocco"},
  {code: IsoCountryCode.MZ, name: "Mozambique"},
  {code: IsoCountryCode.MM, name: "Myanmar"},
  {code: IsoCountryCode.NA, name: "Namibia"},
  {code: IsoCountryCode.NR, name: "Nauru"},
  {code: IsoCountryCode.NP, name: "Nepal"},
  {code: IsoCountryCode.NL, name: "Netherlands"},
  {code: IsoCountryCode.NC, name: "New Caledonia"},
  {code: IsoCountryCode.NZ, name: "New Zealand"},
  {code: IsoCountryCode.NI, name: "Nicaragua"},
  {code: IsoCountryCode.NE, name: "Niger"},
  {code: IsoCountryCode.NG, name: "Nigeria"},
  {code: IsoCountryCode.NU, name: "Niue"},
  {code: IsoCountryCode.NF, name: "Norfolk Island"},
  {code: IsoCountryCode.MP, name: "Northern Mariana Islands"},
  {code: IsoCountryCode.NO, name: "Norway"},
  {code: IsoCountryCode.OM, name: "Oman"},
  {code: IsoCountryCode.PK, name: "Pakistan"},
  {code: IsoCountryCode.PW, name: "Palau"},
  {code: IsoCountryCode.PS, name: "Palestine"},
  {code: IsoCountryCode.PA, name: "Panama"},
  {code: IsoCountryCode.PG, name: "Papua New Guinea"},
  {code: IsoCountryCode.PY, name: "Paraguay"},
  {code: IsoCountryCode.PE, name: "Peru"},
  {code: IsoCountryCode.PH, name: "Philippines"},
  {code: IsoCountryCode.PN, name: "Pitcairn Islands"},
  {code: IsoCountryCode.PL, name: "Poland"},
  {code: IsoCountryCode.PT, name: "Portugal"},
  {code: IsoCountryCode.PR, name: "Puerto Rico"},
  {code: IsoCountryCode.QA, name: "Qatar"},
  {code: IsoCountryCode.RE, name: "Reunion"},
  {code: IsoCountryCode.RO, name: "Romania"},
  {code: IsoCountryCode.RU, name: "Russia"},
  {code: IsoCountryCode.RW, name: "Rwanda"},
  {code: IsoCountryCode.BL, name: "Saint Barthelemy"},
  {code: IsoCountryCode.SH, name: "Saint Helena"},
  {code: IsoCountryCode.KN, name: "Saint Kitts and Nevis"},
  {code: IsoCountryCode.LC, name: "Saint Lucia"},
  {code: IsoCountryCode.MF, name: "Saint Martin"},
  {code: IsoCountryCode.PM, name: "Saint Pierre and Miquelon"},
  {code: IsoCountryCode.VC, name: "Saint Vincent and the Grenadines"},
  {code: IsoCountryCode.WS, name: "Samoa"},
  {code: IsoCountryCode.SM, name: "San Marino"},
  {code: IsoCountryCode.ST, name: "Sao Tome and Principe"},
  {code: IsoCountryCode.SA, name: "Saudi Arabia"},
  {code: IsoCountryCode.SN, name: "Senegal"},
  {code: IsoCountryCode.RS, name: "Serbia"},
  {code: IsoCountryCode.SC, name: "Seychelles"},
  {code: IsoCountryCode.SL, name: "Sierra Leone"},
  {code: IsoCountryCode.SG, name: "Singapore"},
  {code: IsoCountryCode.SX, name: "Sint Maarten"},
  {code: IsoCountryCode.SK, name: "Slovakia"},
  {code: IsoCountryCode.SI, name: "Slovenia"},
  {code: IsoCountryCode.SB, name: "Solomon Islands"},
  {code: IsoCountryCode.SO, name: "Somalia"},
  {code: IsoCountryCode.ZA, name: "South Africa"},
  {code: IsoCountryCode.GS, name: "South Georgia and the South Sandwich Islands"},
  {code: IsoCountryCode.SS, name: "South Sudan"},
  {code: IsoCountryCode.ES, name: "Spain"},
  {code: IsoCountryCode.LK, name: "Sri Lanka"},
  {code: IsoCountryCode.SD, name: "Sudan"},
  {code: IsoCountryCode.SR, name: "Suriname"},
  {code: IsoCountryCode.SJ, name: "Svalbard and Jan Mayen"},
  {code: IsoCountryCode.SZ, name: "Swaziland"},
  {code: IsoCountryCode.SE, name: "Sweden"},
  {code: IsoCountryCode.CH, name: "Switzerland"},
  {code: IsoCountryCode.SY, name: "Syria"},
  {code: IsoCountryCode.TW, name: "Taiwan"},
  {code: IsoCountryCode.TJ, name: "Tajikistan"},
  {code: IsoCountryCode.TZ, name: "Tanzania"},
  {code: IsoCountryCode.TH, name: "Thailand"},
  {code: IsoCountryCode.TL, name: "Timor-Leste"},
  {code: IsoCountryCode.TG, name: "Togo"},
  {code: IsoCountryCode.TK, name: "Tokelau"},
  {code: IsoCountryCode.TO, name: "Tonga"},
  {code: IsoCountryCode.TT, name: "Trinidad and Tobago"},
  {code: IsoCountryCode.TN, name: "Tunisia"},
  {code: IsoCountryCode.TR, name: "Turkey"},
  {code: IsoCountryCode.TM, name: "Turkmenistan"},
  {code: IsoCountryCode.TC, name: "Turks and Caicos Islands"},
  {code: IsoCountryCode.TV, name: "Tuvalu"},
  {code: IsoCountryCode.UG, name: "Uganda"},
  {code: IsoCountryCode.UA, name: "Ukraine"},
  {code: IsoCountryCode.AE, name: "United Arab Emirates"},
  {code: IsoCountryCode.GB, name: "United Kingdom"},
  {code: IsoCountryCode.US, name: "United States"},
  {code: IsoCountryCode.UM, name: "United States Minor Outlying Islands"},
  {code: IsoCountryCode.UY, name: "Uruguay"},
  {code: IsoCountryCode.UZ, name: "Uzbekistan"},
  {code: IsoCountryCode.VU, name: "Vanuatu"},
  {code: IsoCountryCode.VE, name: "Venezuela"},
  {code: IsoCountryCode.VN, name: "Vietnam"},
  {code: IsoCountryCode.VG, name: "British Virgin Islands"},
  {code: IsoCountryCode.VI, name: "United States Virgin Islands"},
  {code: IsoCountryCode.WF, name: "Wallis and Futuna"},
  {code: IsoCountryCode.EH, name: "Western Sahara"},
  {code: IsoCountryCode.YE, name: "Yemen"},
  {code: IsoCountryCode.ZM, name: "Zambia"},
  {code: IsoCountryCode.ZW, name: "Zimbabwe"}
];
