import {User} from './user.model';

export interface IsoCountry {
  code: IsoCountryCode;
  name: string;
}

export const getUserIsoCountryLabel = (user?: User | null): string => {
  if (user == null) {
    return getDefaultIsoCountry().name;
  }

  return getIsoCountryByCode(user.country)?.name || getDefaultIsoCountry().name;
}

export const getIsoCountryLabel = (code?: IsoCountryCode | null): string => {
  if (code == null) {
    return getDefaultIsoCountry().name;
  }

  return getIsoCountryByCode(code).name;
}

export const getDefaultIsoCountry = (): IsoCountry => {
  return IsoCountries.find(c => c.code === IsoCountryCode.LT)!;
}

export const getIsoCountryByCode = (code: IsoCountryCode): IsoCountry => {
  return IsoCountries.find(c => c.code === code) || getDefaultIsoCountry();
}

export enum IsoCountryCode {
  AF,
  AX,
  AL,
  DZ,
  AS,
  AD,
  AO,
  AI,
  AQ,
  AG,
  AR,
  AM,
  AW,
  AU,
  AT,
  AZ,
  BS,
  BH,
  BD,
  BB,
  BY,
  BE,
  BZ,
  BJ,
  BM,
  BT,
  BO,
  BQ,
  BA,
  BW,
  BV,
  BR,
  IO,
  BN,
  BG,
  BF,
  BI,
  CV,
  KH,
  CM,
  CA,
  KY,
  CF,
  TD,
  CL,
  CN,
  CX,
  CC,
  CO,
  KM,
  CG,
  CD,
  CK,
  CR,
  CI,
  HR,
  CU,
  CW,
  CY,
  CZ,
  DK,
  DJ,
  DM,
  DO,
  EC,
  EG,
  SV,
  GQ,
  ER,
  EE,
  SZ,
  ET,
  FK,
  FO,
  FJ,
  FI,
  FR,
  GF,
  PF,
  TF,
  GA,
  GM,
  GE,
  DE,
  GH,
  GI,
  GR,
  GL,
  GD,
  GP,
  GU,
  GT,
  GG,
  GN,
  GW,
  GY,
  HT,
  HM,
  VA,
  HN,
  HK,
  HU,
  IS,
  IN,
  ID,
  IR,
  IQ,
  IE,
  IM,
  IL,
  IT,
  JM,
  JP,
  JE,
  JO,
  KZ,
  KE,
  KI,
  KP,
  KR,
  KW,
  KG,
  LA,
  LV,
  LB,
  LS,
  LR,
  LY,
  LI,
  LT,
  LU,
  MO,
  MG,
  MW,
  MY,
  MV,
  ML,
  MT,
  MH,
  MQ,
  MR,
  MU,
  YT,
  MX,
  FM,
  MD,
  MC,
  MN,
  ME,
  MS,
  MA,
  MZ,
  MM,
  NA,
  NR,
  NP,
  NL,
  NC,
  NZ,
  NI,
  NE,
  NG,
  NU,
  NF,
  MK,
  MP,
  NO,
  OM,
  PK,
  PW,
  PS,
  PA,
  PG,
  PY,
  PE,
  PH,
  PN,
  PL,
  PT,
  PR,
  QA,
  RE,
  RO,
  RU,
  RW,
  BL,
  SH,
  KN,
  LC,
  MF,
  PM,
  VC,
  WS,
  SM,
  ST,
  SA,
  SN,
  RS,
  SC,
  SL,
  SG,
  SX,
  SK,
  SI,
  SB,
  SO,
  ZA,
  GS,
  SS,
  ES,
  LK,
  SD,
  SR,
  SJ,
  SE,
  CH,
  SY,
  TW,
  TJ,
  TZ,
  TH,
  TL,
  TG,
  TK,
  TO,
  TT,
  TN,
  TR,
  TM,
  TC,
  TV,
  UG,
  UA,
  AE,
  GB,
  US,
  UM,
  UY,
  UZ,
  VU,
  VE,
  VN,
  VG,
  VI,
  WF,
  EH,
  YE,
  ZM,
  ZW
}

export const IsoCountries: IsoCountry[] = [
  {name: "Afghanistan", code: IsoCountryCode.AF},
  {name: "Åland Islands", code: IsoCountryCode.AX},
  {name: "Albania", code: IsoCountryCode.AL},
  {name: "Algeria", code: IsoCountryCode.DZ},
  {name: "American Samoa", code: IsoCountryCode.AS},
  {name: "Andorra", code: IsoCountryCode.AD},
  {name: "Angola", code: IsoCountryCode.AO},
  {name: "Anguilla", code: IsoCountryCode.AI},
  {name: "Antarctica", code: IsoCountryCode.AQ},
  {name: "Antigua and Barbuda", code: IsoCountryCode.AG},
  {name: "Argentina", code: IsoCountryCode.AR},
  {name: "Armenia", code: IsoCountryCode.AM},
  {name: "Aruba", code: IsoCountryCode.AW},
  {name: "Australia", code: IsoCountryCode.AU},
  {name: "Austria", code: IsoCountryCode.AT},
  {name: "Azerbaijan", code: IsoCountryCode.AZ},
  {name: "Bahamas", code: IsoCountryCode.BS},
  {name: "Bahrain", code: IsoCountryCode.BH},
  {name: "Bangladesh", code: IsoCountryCode.BD},
  {name: "Barbados", code: IsoCountryCode.BB},
  {name: "Belarus", code: IsoCountryCode.BY},
  {name: "Belgium", code: IsoCountryCode.BE},
  {name: "Belize", code: IsoCountryCode.BZ},
  {name: "Benin", code: IsoCountryCode.BJ},
  {name: "Bermuda", code: IsoCountryCode.BM},
  {name: "Bhutan", code: IsoCountryCode.BT},
  {name: "Bolivia, Plurinational State of", code: IsoCountryCode.BO},
  {name: "Bonaire, Sint Eustatius and Saba", code: IsoCountryCode.BQ},
  {name: "Bosnia and Herzegovina", code: IsoCountryCode.BA},
  {name: "Botswana", code: IsoCountryCode.BW},
  {name: "Bouvet Island", code: IsoCountryCode.BV},
  {name: "Brazil", code: IsoCountryCode.BR},
  {name: "British Indian Ocean Territory", code: IsoCountryCode.IO},
  {name: "Brunei Darussalam", code: IsoCountryCode.BN},
  {name: "Bulgaria", code: IsoCountryCode.BG},
  {name: "Burkina Faso", code: IsoCountryCode.BF},
  {name: "Burundi", code: IsoCountryCode.BI},
  {name: "Cabo Verde", code: IsoCountryCode.CV},
  {name: "Cambodia", code: IsoCountryCode.KH},
  {name: "Cameroon", code: IsoCountryCode.CM},
  {name: "Canada", code: IsoCountryCode.CA},
  {name: "Cayman Islands", code: IsoCountryCode.KY},
  {name: "Central African Republic", code: IsoCountryCode.CF},
  {name: "Chad", code: IsoCountryCode.TD},
  {name: "Chile", code: IsoCountryCode.CL},
  {name: "China", code: IsoCountryCode.CN},
  {name: "Christmas Island", code: IsoCountryCode.CX},
  {name: "Cocos (Keeling) Islands", code: IsoCountryCode.CC},
  {name: "Colombia", code: IsoCountryCode.CO},
  {name: "Comoros", code: IsoCountryCode.KM},
  {name: "Congo", code: IsoCountryCode.CG},
  {name: "Congo, Democratic Republic of the", code: IsoCountryCode.CD},
  {name: "Cook Islands", code: IsoCountryCode.CK},
  {name: "Costa Rica", code: IsoCountryCode.CR},
  {name: "Côte d'Ivoire", code: IsoCountryCode.CI},
  {name: "Croatia", code: IsoCountryCode.HR},
  {name: "Cuba", code: IsoCountryCode.CU},
  {name: "Curaçao", code: IsoCountryCode.CW},
  {name: "Cyprus", code: IsoCountryCode.CY},
  {name: "Czechia", code: IsoCountryCode.CZ},
  {name: "Denmark", code: IsoCountryCode.DK},
  {name: "Djibouti", code: IsoCountryCode.DJ},
  {name: "Dominica", code: IsoCountryCode.DM},
  {name: "Dominican Republic", code: IsoCountryCode.DO},
  {name: "Ecuador", code: IsoCountryCode.EC},
  {name: "Egypt", code: IsoCountryCode.EG},
  {name: "El Salvador", code: IsoCountryCode.SV},
  {name: "Equatorial Guinea", code: IsoCountryCode.GQ},
  {name: "Eritrea", code: IsoCountryCode.ER},
  {name: "Estonia", code: IsoCountryCode.EE},
  {name: "Eswatini", code: IsoCountryCode.SZ},
  {name: "Ethiopia", code: IsoCountryCode.ET},
  {name: "Falkland Islands (Malvinas)", code: IsoCountryCode.FK},
  {name: "Faroe Islands", code: IsoCountryCode.FO},
  {name: "Fiji", code: IsoCountryCode.FJ},
  {name: "Finland", code: IsoCountryCode.FI},
  {name: "France", code: IsoCountryCode.FR},
  {name: "French Guiana", code: IsoCountryCode.GF},
  {name: "French Polynesia", code: IsoCountryCode.PF},
  {name: "French Southern Territories", code: IsoCountryCode.TF},
  {name: "Gabon", code: IsoCountryCode.GA},
  {name: "Gambia", code: IsoCountryCode.GM},
  {name: "Georgia", code: IsoCountryCode.GE},
  {name: "Germany", code: IsoCountryCode.DE},
  {name: "Ghana", code: IsoCountryCode.GH},
  {name: "Gibraltar", code: IsoCountryCode.GI},
  {name: "Greece", code: IsoCountryCode.GR},
  {name: "Greenland", code: IsoCountryCode.GL},
  {name: "Grenada", code: IsoCountryCode.GD},
  {name: "Guadeloupe", code: IsoCountryCode.GP},
  {name: "Guam", code: IsoCountryCode.GU},
  {name: "Guatemala", code: IsoCountryCode.GT},
  {name: "Guernsey", code: IsoCountryCode.GG},
  {name: "Guinea", code: IsoCountryCode.GN},
  {name: "Guinea-Bissau", code: IsoCountryCode.GW},
  {name: "Guyana", code: IsoCountryCode.GY},
  {name: "Haiti", code: IsoCountryCode.HT},
  {name: "Heard Island and McDonald Islands", code: IsoCountryCode.HM},
  {name: "Holy See", code: IsoCountryCode.VA},
  {name: "Honduras", code: IsoCountryCode.HN},
  {name: "Hong Kong", code: IsoCountryCode.HK},
  {name: "Hungary", code: IsoCountryCode.HU},
  {name: "Iceland", code: IsoCountryCode.IS},
  {name: "India", code: IsoCountryCode.IN},
  {name: "Indonesia", code: IsoCountryCode.ID},
  {name: "Iran, Islamic Republic of", code: IsoCountryCode.IR},
  {name: "Iraq", code: IsoCountryCode.IQ},
  {name: "Ireland", code: IsoCountryCode.IE},
  {name: "Isle of Man", code: IsoCountryCode.IM},
  {name: "Israel", code: IsoCountryCode.IL},
  {name: "Italy", code: IsoCountryCode.IT},
  {name: "Jamaica", code: IsoCountryCode.JM},
  {name: "Japan", code: IsoCountryCode.JP},
  {name: "Jersey", code: IsoCountryCode.JE},
  {name: "Jordan", code: IsoCountryCode.JO},
  {name: "Kazakhstan", code: IsoCountryCode.KZ},
  {name: "Kenya", code: IsoCountryCode.KE},
  {name: "Kiribati", code: IsoCountryCode.KI},
  {name: "Korea, Democratic People's Republic of", code: IsoCountryCode.KP},
  {name: "Korea, Republic of", code: IsoCountryCode.KR},
  {name: "Kuwait", code: IsoCountryCode.KW},
  {name: "Kyrgyzstan", code: IsoCountryCode.KG},
  {name: "Lao People's Democratic Republic", code: IsoCountryCode.LA},
  {name: "Latvia", code: IsoCountryCode.LV},
  {name: "Lebanon", code: IsoCountryCode.LB},
  {name: "Lesotho", code: IsoCountryCode.LS},
  {name: "Liberia", code: IsoCountryCode.LR},
  {name: "Libya", code: IsoCountryCode.LY},
  {name: "Liechtenstein", code: IsoCountryCode.LI},
  {name: "Lithuania", code: IsoCountryCode.LT},
  {name: "Luxembourg", code: IsoCountryCode.LU},
  {name: "Macao", code: IsoCountryCode.MO},
  {name: "Madagascar", code: IsoCountryCode.MG},
  {name: "Malawi", code: IsoCountryCode.MW},
  {name: "Malaysia", code: IsoCountryCode.MY},
  {name: "Maldives", code: IsoCountryCode.MV},
  {name: "Mali", code: IsoCountryCode.ML},
  {name: "Malta", code: IsoCountryCode.MT},
  {name: "Marshall Islands", code: IsoCountryCode.MH},
  {name: "Martinique", code: IsoCountryCode.MQ},
  {name: "Mauritania", code: IsoCountryCode.MR},
  {name: "Mauritius", code: IsoCountryCode.MU},
  {name: "Mayotte", code: IsoCountryCode.YT},
  {name: "Mexico", code: IsoCountryCode.MX},
  {name: "Micronesia, Federated States of", code: IsoCountryCode.FM},
  {name: "Moldova, Republic of", code: IsoCountryCode.MD},
  {name: "Monaco", code: IsoCountryCode.MC},
  {name: "Mongolia", code: IsoCountryCode.MN},
  {name: "Montenegro", code: IsoCountryCode.ME},
  {name: "Montserrat", code: IsoCountryCode.MS},
  {name: "Morocco", code: IsoCountryCode.MA},
  {name: "Mozambique", code: IsoCountryCode.MZ},
  {name: "Myanmar", code: IsoCountryCode.MM},
  {name: "Namibia", code: IsoCountryCode.NA},
  {name: "Nauru", code: IsoCountryCode.NR},
  {name: "Nepal", code: IsoCountryCode.NP},
  {name: "Netherlands, Kingdom of the", code: IsoCountryCode.NL},
  {name: "New Caledonia", code: IsoCountryCode.NC},
  {name: "New Zealand", code: IsoCountryCode.NZ},
  {name: "Nicaragua", code: IsoCountryCode.NI},
  {name: "Niger", code: IsoCountryCode.NE},
  {name: "Nigeria", code: IsoCountryCode.NG},
  {name: "Niue", code: IsoCountryCode.NU},
  {name: "Norfolk Island", code: IsoCountryCode.NF},
  {name: "North Macedonia", code: IsoCountryCode.MK},
  {name: "Northern Mariana Islands", code: IsoCountryCode.MP},
  {name: "Norway", code: IsoCountryCode.NO},
  {name: "Oman", code: IsoCountryCode.OM},
  {name: "Pakistan", code: IsoCountryCode.PK},
  {name: "Palau", code: IsoCountryCode.PW},
  {name: "Palestine, State of", code: IsoCountryCode.PS},
  {name: "Panama", code: IsoCountryCode.PA},
  {name: "Papua New Guinea", code: IsoCountryCode.PG},
  {name: "Paraguay", code: IsoCountryCode.PY},
  {name: "Peru", code: IsoCountryCode.PE},
  {name: "Philippines", code: IsoCountryCode.PH},
  {name: "Pitcairn", code: IsoCountryCode.PN},
  {name: "Poland", code: IsoCountryCode.PL},
  {name: "Portugal", code: IsoCountryCode.PT},
  {name: "Puerto Rico", code: IsoCountryCode.PR},
  {name: "Qatar", code: IsoCountryCode.QA},
  {name: "Réunion", code: IsoCountryCode.RE},
  {name: "Romania", code: IsoCountryCode.RO},
  {name: "Russian Federation", code: IsoCountryCode.RU},
  {name: "Rwanda", code: IsoCountryCode.RW},
  {name: "Saint Barthélemy", code: IsoCountryCode.BL},
  {name: "Saint Helena, Ascension and Tristan da Cunha", code: IsoCountryCode.SH},
  {name: "Saint Kitts and Nevis", code: IsoCountryCode.KN},
  {name: "Saint Lucia", code: IsoCountryCode.LC},
  {name: "Saint Martin (French part)", code: IsoCountryCode.MF},
  {name: "Saint Pierre and Miquelon", code: IsoCountryCode.PM},
  {name: "Saint Vincent and the Grenadines", code: IsoCountryCode.VC},
  {name: "Samoa", code: IsoCountryCode.WS},
  {name: "San Marino", code: IsoCountryCode.SM},
  {name: "Sao Tome and Principe", code: IsoCountryCode.ST},
  {name: "Saudi Arabia", code: IsoCountryCode.SA},
  {name: "Senegal", code: IsoCountryCode.SN},
  {name: "Serbia", code: IsoCountryCode.RS},
  {name: "Seychelles", code: IsoCountryCode.SC},
  {name: "Sierra Leone", code: IsoCountryCode.SL},
  {name: "Singapore", code: IsoCountryCode.SG},
  {name: "Sint Maarten (Dutch part)", code: IsoCountryCode.SX},
  {name: "Slovakia", code: IsoCountryCode.SK},
  {name: "Slovenia", code: IsoCountryCode.SI},
  {name: "Solomon Islands", code: IsoCountryCode.SB},
  {name: "Somalia", code: IsoCountryCode.SO},
  {name: "South Africa", code: IsoCountryCode.ZA},
  {name: "South Georgia and the South Sandwich Islands", code: IsoCountryCode.GS},
  {name: "South Sudan", code: IsoCountryCode.SS},
  {name: "Spain", code: IsoCountryCode.ES},
  {name: "Sri Lanka", code: IsoCountryCode.LK},
  {name: "Sudan", code: IsoCountryCode.SD},
  {name: "Suriname", code: IsoCountryCode.SR},
  {name: "Svalbard and Jan Mayen", code: IsoCountryCode.SJ},
  {name: "Sweden", code: IsoCountryCode.SE},
  {name: "Switzerland", code: IsoCountryCode.CH},
  {name: "Syrian Arab Republic", code: IsoCountryCode.SY},
  {name: "Taiwan, Province of China", code: IsoCountryCode.TW},
  {name: "Tajikistan", code: IsoCountryCode.TJ},
  {name: "Tanzania, United Republic of", code: IsoCountryCode.TZ},
  {name: "Thailand", code: IsoCountryCode.TH},
  {name: "Timor-Leste", code: IsoCountryCode.TL},
  {name: "Togo", code: IsoCountryCode.TG},
  {name: "Tokelau", code: IsoCountryCode.TK},
  {name: "Tonga", code: IsoCountryCode.TO},
  {name: "Trinidad and Tobago", code: IsoCountryCode.TT},
  {name: "Tunisia", code: IsoCountryCode.TN},
  {name: "Türkiye", code: IsoCountryCode.TR},
  {name: "Turkmenistan", code: IsoCountryCode.TM},
  {name: "Turks and Caicos Islands", code: IsoCountryCode.TC},
  {name: "Tuvalu", code: IsoCountryCode.TV},
  {name: "Uganda", code: IsoCountryCode.UG},
  {name: "Ukraine", code: IsoCountryCode.UA},
  {name: "United Arab Emirates", code: IsoCountryCode.AE},
  {name: "United Kingdom of Great Britain and Northern Ireland", code: IsoCountryCode.GB},
  {name: "United States of America", code: IsoCountryCode.US},
  {name: "United States Minor Outlying Islands", code: IsoCountryCode.UM},
  {name: "Uruguay", code: IsoCountryCode.UY},
  {name: "Uzbekistan", code: IsoCountryCode.UZ},
  {name: "Vanuatu", code: IsoCountryCode.VU},
  {name: "Venezuela, Bolivarian Republic of", code: IsoCountryCode.VE},
  {name: "Viet Nam", code: IsoCountryCode.VN},
  {name: "Virgin Islands (British)", code: IsoCountryCode.VG},
  {name: "Virgin Islands (U.S.)", code: IsoCountryCode.VI},
  {name: "Wallis and Futuna", code: IsoCountryCode.WF},
  {name: "Western Sahara", code: IsoCountryCode.EH},
  {name: "Yemen", code: IsoCountryCode.YE},
  {name: "Zambia", code: IsoCountryCode.ZM},
  {name: "Zimbabwe", code: IsoCountryCode.ZW}
];
