import {User} from './user.model';

export interface IsoCountry {
  code: IsoCountryCode;
  name: string;
}

export const getUserIsoCountryLabel = (user?: User | null): string => {
  if (user == null) {
    return getDefaultIsoCountry().name;
  }

  return getIsoCountryByCode(user.country)?.name || getDefaultIsoCountry().name;
}

export const getIsoCountryLabel = (code?: IsoCountryCode | null): string => {
  if (code == null) {
    return getDefaultIsoCountry().name;
  }

  return getIsoCountryByCode(code).name;
}

export const getDefaultIsoCountry = (): IsoCountry => {
  return IsoCountries.find(c => c.code === IsoCountryCode.LT)!;
}

export const getIsoCountryByCode = (code: IsoCountryCode): IsoCountry => {
  return IsoCountries.find(c => c.code === code) || getDefaultIsoCountry();
}

export enum IsoCountryCode {
  AF,
  AX,
  AL,
  DZ,
  AS,
  AD,
  AO,
  AI,
  AQ,
  AG,
  AR,
  AM,
  AW,
  AU,
  AT,
  AZ,
  BS,
  BH,
  BD,
  BB,
  BY,
  BE,
  BZ,
  BJ,
  BM,
  BT,
  BO,
  BQ,
  BA,
  BW,
  BV,
  BR,
  IO,
  BN,
  BG,
  BF,
  BI,
  KH,
  CM,
  CA,
  CV,
  KY,
  CF,
  TD,
  CL,
  CN,
  CX,
  CC,
  CO,
  KM,
  CG,
  CD,
  CK,
  CR,
  CI,
  HR,
  CU,
  CW,
  CY,
  CZ,
  DK,
  DJ,
  DM,
  DO,
  EC,
  EG,
  SV,
  GQ,
  ER,
  EE,
  ET,
  FK,
  FO,
  FJ,
  FI,
  FR,
  GF,
  PF,
  TF,
  GA,
  GM,
  GE,
  DE,
  GH,
  GI,
  GR,
  GL,
  GD,
  GP,
  GU,
  GT,
  GG,
  GN,
  GW,
  GY,
  HT,
  HM,
  VA,
  HN,
  HK,
  HU,
  IS,
  IN,
  ID,
  IR,
  IQ,
  IE,
  IM,
  IL,
  IT,
  JM,
  JP,
  JE,
  JO,
  KZ,
  KE,
  KI,
  KP,
  KR,
  KW,
  KG,
  LA,
  LV,
  LB,
  LS,
  LR,
  LY,
  LI,
  LT,
  LU,
  MO,
  MK,
  MG,
  MW,
  MY,
  MV,
  ML,
  MT,
  MH,
  MQ,
  MR,
  MU,
  YT,
  MX,
  FM,
  MD,
  MC,
  MN,
  ME,
  MS,
  MA,
  MZ,
  MM,
  NA,
  NR,
  NP,
  NL,
  NC,
  NZ,
  NI,
  NE,
  NG,
  NU,
  NF,
  MP,
  NO,
  OM,
  PK,
  PW,
  PS,
  PA,
  PG,
  PY,
  PE,
  PH,
  PN,
  PL,
  PT,
  PR,
  QA,
  RE,
  RO,
  RU,
  RW,
  BL,
  SH,
  KN,
  LC,
  MF,
  PM,
  VC,
  WS,
  SM,
  ST,
  SA,
  SN,
  RS,
  SC,
  SL,
  SG,
  SX,
  SK,
  SI,
  SB,
  SO,
  ZA,
  GS,
  SS,
  ES,
  LK,
  SD,
  SR,
  SJ,
  SZ,
  SE,
  CH,
  SY,
  TW,
  TJ,
  TZ,
  TH,
  TL,
  TG,
  TK,
  TO,
  TT,
  TN,
  TR,
  TM,
  TC,
  TV,
  UG,
  UA,
  AE,
  GB,
  US,
  UM,
  UY,
  UZ,
  VU,
  VE,
  VN,
  VG,
  VI,
  WF,
  EH,
  YE,
  ZM,
  ZW
}

export const IsoCountries: IsoCountry[] = [
  {code: IsoCountryCode.AF, name: "Afghānistān"},
  {code: IsoCountryCode.AX, name: "Åland"},
  {code: IsoCountryCode.AL, name: "Shqipëria"},
  {code: IsoCountryCode.DZ, name: "Al-Jazā'ir"},
  {code: IsoCountryCode.AS, name: "Amerika Sāmoa"},
  {code: IsoCountryCode.AD, name: "Andorra"},
  {code: IsoCountryCode.AO, name: "Angola"},
  {code: IsoCountryCode.AI, name: "Anguilla"},
  {code: IsoCountryCode.AQ, name: "Antarctica"},
  {code: IsoCountryCode.AG, name: "Antigua and Barbuda"},
  {code: IsoCountryCode.AR, name: "Argentina"},
  {code: IsoCountryCode.AM, name: "Hayastan"},
  {code: IsoCountryCode.AW, name: "Aruba"},
  {code: IsoCountryCode.AU, name: "Australia"},
  {code: IsoCountryCode.AT, name: "Österreich"},
  {code: IsoCountryCode.AZ, name: "Azərbaycan"},
  {code: IsoCountryCode.BS, name: "Bahamas"},
  {code: IsoCountryCode.BH, name: "Al-Baḥrayn"},
  {code: IsoCountryCode.BD, name: "Bangladesh"},
  {code: IsoCountryCode.BB, name: "Barbados"},
  {code: IsoCountryCode.BY, name: "Belarus"},
  {code: IsoCountryCode.BE, name: "België"},
  {code: IsoCountryCode.BZ, name: "Belize"},
  {code: IsoCountryCode.BJ, name: "Bénin"},
  {code: IsoCountryCode.BM, name: "Bermuda"},
  {code: IsoCountryCode.BT, name: "Druk Yul"},
  {code: IsoCountryCode.BO, name: "Bolivia"},
  {code: IsoCountryCode.BQ, name: "Bonaire"},
  {code: IsoCountryCode.BA, name: "Bosna i Hercegovina"},
  {code: IsoCountryCode.BW, name: "Botswana"},
  {code: IsoCountryCode.BV, name: "Bouvetøya"},
  {code: IsoCountryCode.BR, name: "Brasil"},
  {code: IsoCountryCode.IO, name: "British Indian Ocean Territory"},
  {code: IsoCountryCode.BN, name: "Brunei"},
  {code: IsoCountryCode.BG, name: "Bulgaria"},
  {code: IsoCountryCode.BF, name: "Burkina Faso"},
  {code: IsoCountryCode.BI, name: "Uburundi"},
  {code: IsoCountryCode.KH, name: "Kâmpŭchéa"},
  {code: IsoCountryCode.CM, name: "Cameroun"},
  {code: IsoCountryCode.CA, name: "Canada"},
  {code: IsoCountryCode.CV, name: "Cabo Verde"},
  {code: IsoCountryCode.KY, name: "Cayman Islands"},
  {code: IsoCountryCode.CF, name: "République centrafricaine"},
  {code: IsoCountryCode.TD, name: "Tchad"},
  {code: IsoCountryCode.CL, name: "Chile"},
  {code: IsoCountryCode.CN, name: "Zhōngguó"},
  {code: IsoCountryCode.CX, name: "Christmas Island"},
  {code: IsoCountryCode.CC, name: "Cocos (Keeling) Islands"},
  {code: IsoCountryCode.CO, name: "Colombia"},
  {code: IsoCountryCode.KM, name: "Komori"},
  {code: IsoCountryCode.CG, name: "Congo"},
  {code: IsoCountryCode.CD, name: "Congo-Kinshasa"},
  {code: IsoCountryCode.CK, name: "Cook Islands"},
  {code: IsoCountryCode.CR, name: "Costa Rica"},
  {code: IsoCountryCode.CI, name: "Côte d'Ivoire"},
  {code: IsoCountryCode.HR, name: "Hrvatska"},
  {code: IsoCountryCode.CU, name: "Cuba"},
  {code: IsoCountryCode.CW, name: "Curaçao"},
  {code: IsoCountryCode.CY, name: "Kypros"},
  {code: IsoCountryCode.CZ, name: "Česká republika"},
  {code: IsoCountryCode.DK, name: "Danmark"},
  {code: IsoCountryCode.DJ, name: "Djibouti"},
  {code: IsoCountryCode.DM, name: "Dominica"},
  {code: IsoCountryCode.DO, name: "República Dominicana"},
  {code: IsoCountryCode.EC, name: "Ecuador"},
  {code: IsoCountryCode.EG, name: "Miṣr"},
  {code: IsoCountryCode.SV, name: "El Salvador"},
  {code: IsoCountryCode.GQ, name: "Guinea Ecuatorial"},
  {code: IsoCountryCode.ER, name: "Ertra"},
  {code: IsoCountryCode.EE, name: "Eesti"},
  {code: IsoCountryCode.ET, name: "Ityop'iya"},
  {code: IsoCountryCode.FK, name: "Falkland Islands"},
  {code: IsoCountryCode.FO, name: "Føroyar"},
  {code: IsoCountryCode.FJ, name: "Viti"},
  {code: IsoCountryCode.FI, name: "Suomi"},
  {code: IsoCountryCode.FR, name: "France"},
  {code: IsoCountryCode.GF, name: "Guyane française"},
  {code: IsoCountryCode.PF, name: "Polynésie française"},
  {code: IsoCountryCode.TF, name: "Terres australes et antarctiques françaises"},
  {code: IsoCountryCode.GA, name: "Gabon"},
  {code: IsoCountryCode.GM, name: "Gambia"},
  {code: IsoCountryCode.GE, name: "Sakartvelo"},
  {code: IsoCountryCode.DE, name: "Deutschland"},
  {code: IsoCountryCode.GH, name: "Ghana"},
  {code: IsoCountryCode.GI, name: "Gibraltar"},
  {code: IsoCountryCode.GR, name: "Elláda"},
  {code: IsoCountryCode.GL, name: "Kalaallit Nunaat"},
  {code: IsoCountryCode.GD, name: "Grenada"},
  {code: IsoCountryCode.GP, name: "Guadeloupe"},
  {code: IsoCountryCode.GU, name: "Guam"},
  {code: IsoCountryCode.GT, name: "Guatemala"},
  {code: IsoCountryCode.GG, name: "Guernsey"},
  {code: IsoCountryCode.GN, name: "Guinée"},
  {code: IsoCountryCode.GW, name: "Guiné-Bissau"},
  {code: IsoCountryCode.GY, name: "Guyana"},
  {code: IsoCountryCode.HT, name: "Haïti"},
  {code: IsoCountryCode.HM, name: "Heard Island and McDonald Islands"},
  {code: IsoCountryCode.VA, name: "Vaticano"},
  {code: IsoCountryCode.HN, name: "Honduras"},
  {code: IsoCountryCode.HK, name: "Hong Kong"},
  {code: IsoCountryCode.HU, name: "Magyarország"},
  {code: IsoCountryCode.IS, name: "Ísland"},
  {code: IsoCountryCode.IN, name: "Bhārat"},
  {code: IsoCountryCode.ID, name: "Indonesia"},
  {code: IsoCountryCode.IR, name: "Īrān"},
  {code: IsoCountryCode.IQ, name: "Al-‘Irāq"},
  {code: IsoCountryCode.IE, name: "Éire"},
  {code: IsoCountryCode.IM, name: "Isle of Man"},
  {code: IsoCountryCode.IL, name: "Yisra'el"},
  {code: IsoCountryCode.IT, name: "Italia"},
  {code: IsoCountryCode.JM, name: "Jamaica"},
  {code: IsoCountryCode.JP, name: "Nihon"},
  {code: IsoCountryCode.JE, name: "Jersey"},
  {code: IsoCountryCode.JO, name: "Al-‘Urdun"},
  {code: IsoCountryCode.KZ, name: "Qazaqstan"},
  {code: IsoCountryCode.KE, name: "Kenya"},
  {code: IsoCountryCode.KI, name: "Kiribati"},
  {code: IsoCountryCode.KP, name: "Chosŏn"},
  {code: IsoCountryCode.KR, name: "Hanguk"},
  {code: IsoCountryCode.KW, name: "Al-Kuwayt"},
  {code: IsoCountryCode.KG, name: "Kyrgyzstan"},
  {code: IsoCountryCode.LA, name: "Lao"},
  {code: IsoCountryCode.LV, name: "Latvija"},
  {code: IsoCountryCode.LB, name: "Lubnān"},
  {code: IsoCountryCode.LS, name: "Lesotho"},
  {code: IsoCountryCode.LR, name: "Liberia"},
  {code: IsoCountryCode.LY, name: "Lībiyā"},
  {code: IsoCountryCode.LI, name: "Liechtenstein"},
  {code: IsoCountryCode.LT, name: "Lietuva"},
  {code: IsoCountryCode.LU, name: "Lëtzebuerg"},
  {code: IsoCountryCode.MO, name: "Macau"},
  {code: IsoCountryCode.MK, name: "Makedonija"},
  {code: IsoCountryCode.MG, name: "Madagasikara"},
  {code: IsoCountryCode.MW, name: "Malawi"},
  {code: IsoCountryCode.MY, name: "Malaysia"},
  {code: IsoCountryCode.MV, name: "Dhivehi Raajje"},
  {code: IsoCountryCode.ML, name: "Mali"},
  {code: IsoCountryCode.MT, name: "Malta"},
  {code: IsoCountryCode.MH, name: "Marshall Islands"},
  {code: IsoCountryCode.MQ, name: "Martinique"},
  {code: IsoCountryCode.MR, name: "Mūrītāniyā"},
  {code: IsoCountryCode.MU, name: "Maurice"},
  {code: IsoCountryCode.YT, name: "Mayotte"},
  {code: IsoCountryCode.MX, name: "México"},
  {code: IsoCountryCode.FM, name: "Micronesia"},
  {code: IsoCountryCode.MD, name: "Moldova"},
  {code: IsoCountryCode.MC, name: "Monaco"},
  {code: IsoCountryCode.MN, name: "Mongol Uls"},
  {code: IsoCountryCode.ME, name: "Crna Gora"},
  {code: IsoCountryCode.MS, name: "Montserrat"},
  {code: IsoCountryCode.MA, name: "Al-Maghrib"},
  {code: IsoCountryCode.MZ, name: "Moçambique"},
  {code: IsoCountryCode.MM, name: "Myanma"},
  {code: IsoCountryCode.NA, name: "Namibia"},
  {code: IsoCountryCode.NR, name: "Nauru"},
  {code: IsoCountryCode.NP, name: "Nepāl"},
  {code: IsoCountryCode.NL, name: "Nederland"},
  {code: IsoCountryCode.NC, name: "Nouvelle-Calédonie"},
  {code: IsoCountryCode.NZ, name: "Aotearoa"},
  {code: IsoCountryCode.NI, name: "Nicaragua"},
  {code: IsoCountryCode.NE, name: "Niger"},
  {code: IsoCountryCode.NG, name: "Nigeria"},
  {code: IsoCountryCode.NU, name: "Niue"},
  {code: IsoCountryCode.NF, name: "Norfolk Island"},
  {code: IsoCountryCode.MP, name: "Northern Mariana Islands"},
  {code: IsoCountryCode.NO, name: "Norge"},
  {code: IsoCountryCode.OM, name: "‘Umān"},
  {code: IsoCountryCode.PK, name: "Pākistān"},
  {code: IsoCountryCode.PW, name: "Palau"},
  {code: IsoCountryCode.PS, name: "Filasṭīn"},
  {code: IsoCountryCode.PA, name: "Panamá"},
  {code: IsoCountryCode.PG, name: "Papua Niugini"},
  {code: IsoCountryCode.PY, name: "Paraguay"},
  {code: IsoCountryCode.PE, name: "Perú"},
  {code: IsoCountryCode.PH, name: "Pilipinas"},
  {code: IsoCountryCode.PN, name: "Pitcairn Islands"},
  {code: IsoCountryCode.PL, name: "Polska"},
  {code: IsoCountryCode.PT, name: "Portugal"},
  {code: IsoCountryCode.PR, name: "Puerto Rico"},
  {code: IsoCountryCode.QA, name: "Qaṭar"},
  {code: IsoCountryCode.RE, name: "La Réunion"},
  {code: IsoCountryCode.RO, name: "România"},
  {code: IsoCountryCode.RU, name: "Rossiya"},
  {code: IsoCountryCode.RW, name: "Rwanda"},
  {code: IsoCountryCode.BL, name: "Saint-Barthélemy"},
  {code: IsoCountryCode.SH, name: "Saint Helena"},
  {code: IsoCountryCode.KN, name: "Saint Kitts and Nevis"},
  {code: IsoCountryCode.LC, name: "Saint Lucia"},
  {code: IsoCountryCode.MF, name: "Saint-Martin"},
  {code: IsoCountryCode.PM, name: "Saint-Pierre-et-Miquelon"},
  {code: IsoCountryCode.VC, name: "Saint Vincent and the Grenadines"},
  {code: IsoCountryCode.WS, name: "Sāmoa"},
  {code: IsoCountryCode.SM, name: "San Marino"},
  {code: IsoCountryCode.ST, name: "São Tomé e Príncipe"},
  {code: IsoCountryCode.SA, name: "As-Su‘ūdīyah"},
  {code: IsoCountryCode.SN, name: "Sénégal"},
  {code: IsoCountryCode.RS, name: "Srbija"},
  {code: IsoCountryCode.SC, name: "Seychelles"},
  {code: IsoCountryCode.SL, name: "Sierra Leone"},
  {code: IsoCountryCode.SG, name: "Singapore"},
  {code: IsoCountryCode.SX, name: "Sint Maarten"},
  {code: IsoCountryCode.SK, name: "Slovensko"},
  {code: IsoCountryCode.SI, name: "Slovenija"},
  {code: IsoCountryCode.SB, name: "Solomon Islands"},
  {code: IsoCountryCode.SO, name: "Soomaaliya"},
  {code: IsoCountryCode.ZA, name: "South Africa"},
  {code: IsoCountryCode.GS, name: "South Georgia and the South Sandwich Islands"},
  {code: IsoCountryCode.SS, name: "South Sudan"},
  {code: IsoCountryCode.ES, name: "España"},
  {code: IsoCountryCode.LK, name: "Śrī Laṃkā"},
  {code: IsoCountryCode.SD, name: "As-Sūdān"},
  {code: IsoCountryCode.SR, name: "Suriname"},
  {code: IsoCountryCode.SJ, name: "Svalbard and Jan Mayen"},
  {code: IsoCountryCode.SZ, name: "Eswatini"},
  {code: IsoCountryCode.SE, name: "Sverige"},
  {code: IsoCountryCode.CH, name: "Schweiz"},
  {code: IsoCountryCode.SY, name: "Sūriyā"},
  {code: IsoCountryCode.TW, name: "Táiwān"},
  {code: IsoCountryCode.TJ, name: "Tojikiston"},
  {code: IsoCountryCode.TZ, name: "Tanzania"},
  {code: IsoCountryCode.TH, name: "Prathet Thai"},
  {code: IsoCountryCode.TL, name: "Timor-Leste"},
  {code: IsoCountryCode.TG, name: "Togo"},
  {code: IsoCountryCode.TK, name: "Tokelau"},
  {code: IsoCountryCode.TO, name: "Tonga"},
  {code: IsoCountryCode.TT, name: "Trinidad and Tobago"},
  {code: IsoCountryCode.TN, name: "Tūnis"},
  {code: IsoCountryCode.TR, name: "Türkiye"},
  {code: IsoCountryCode.TM, name: "Türkmenistan"},
  {code: IsoCountryCode.TC, name: "Turks and Caicos Islands"},
  {code: IsoCountryCode.TV, name: "Tuvalu"},
  {code: IsoCountryCode.UG, name: "Uganda"},
  {code: IsoCountryCode.UA, name: "Ukrayina"},
  {code: IsoCountryCode.AE, name: "Al-Imārāt"},
  {code: IsoCountryCode.GB, name: "United Kingdom"},
  {code: IsoCountryCode.US, name: "United States"},
  {code: IsoCountryCode.UM, name: "United States Minor Outlying Islands"},
  {code: IsoCountryCode.UY, name: "Uruguay"},
  {code: IsoCountryCode.UZ, name: "Oʻzbekiston"},
  {code: IsoCountryCode.VU, name: "Vanuatu"},
  {code: IsoCountryCode.VE, name: "Venezuela"},
  {code: IsoCountryCode.VN, name: "Việt Nam"},
  {code: IsoCountryCode.VG, name: "British Virgin Islands"},
  {code: IsoCountryCode.VI, name: "United States Virgin Islands"},
  {code: IsoCountryCode.WF, name: "Wallis and Futuna"},
  {code: IsoCountryCode.EH, name: "Western Sahara"},
  {code: IsoCountryCode.YE, name: "Al-Yaman"},
  {code: IsoCountryCode.ZM, name: "Zambia"},
  {code: IsoCountryCode.ZW, name: "Zimbabwe"}
];
